/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignmentthree;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class DeleteFrame extends javax.swing.JFrame {
      ArrayList<OrderSupply> OrderSupplies;
    /**
     * Creates new form DeleteFrame
     */
    public DeleteFrame() {
        initComponents();
        OrderSupplies = new ArrayList<OrderSupply>();
        getContentPane().setBackground(new java.awt.Color(0,51,102));
        populateArrayList();
        
        String[] orderKeyChoice =  new String[OrderSupplies.size()];
        
        for(int i = 0 ; i < OrderSupplies.size() ; i++)
        {
            orderKeyChoice[i] = OrderSupplies.get(i).getOrderKey();
        }
        OrderKeyRemove.setModel(new javax.swing.DefaultComboBoxModel<>(orderKeyChoice));
        
        OrderKeyRemove.setSelectedIndex(0);
    }
     public void saveOrderToFile()
    {
        try
        {
            FileOutputStream file = new FileOutputStream("order.txt");
            ObjectOutputStream outputFile = new ObjectOutputStream(file);
            
            for(int i = 0; i < OrderSupplies.size(); i++)
            {
                outputFile.writeObject(OrderSupplies.get(i));
            }
            outputFile.close();
             JOptionPane.showMessageDialog(null, "Successfully Removed!");
             this.dispose();
             
        }  
        catch(IOException e)
        {
           JOptionPane.showMessageDialog(null, e.getMessage());         
        }
    }
    
    public void populateArrayList(){
        try{
          FileInputStream file = new FileInputStream("order.txt");
          ObjectInputStream inputFile = new ObjectInputStream(file);
          
          boolean endOfFile = false;
          while(!endOfFile)
          {
             try
             {
               OrderSupplies.add((OrderSupply)inputFile.readObject());  
             } 
             catch(EOFException e)
             {
                endOfFile = true;
             }
             catch (Exception f) 
             {
               JOptionPane.showMessageDialog(null, f.getMessage());  
             }
          }//while
        inputFile.close(); 
        }//try
        catch(IOException e){
          JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        AmountEditText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        OrderKeyRemove = new javax.swing.JComboBox<>();
        EditDataButton = new javax.swing.JButton();
        FruitOrderText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        HospitalEditText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 102));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Order Key ");

        AmountEditText.setEditable(false);
        AmountEditText.setBackground(new java.awt.Color(255, 102, 102));
        AmountEditText.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        AmountEditText.setForeground(new java.awt.Color(255, 255, 255));
        AmountEditText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 3));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fruit Ordered");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Amount ");

        OrderKeyRemove.setBackground(new java.awt.Color(255, 102, 102));
        OrderKeyRemove.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        OrderKeyRemove.setForeground(new java.awt.Color(255, 255, 255));
        OrderKeyRemove.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        OrderKeyRemove.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 3));
        OrderKeyRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderKeyRemoveActionPerformed(evt);
            }
        });

        EditDataButton.setBackground(new java.awt.Color(255, 51, 102));
        EditDataButton.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        EditDataButton.setForeground(new java.awt.Color(255, 255, 255));
        EditDataButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-remove-20.png"))); // NOI18N
        EditDataButton.setText("Remove Data");
        EditDataButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 3));
        EditDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditDataButtonActionPerformed(evt);
            }
        });

        FruitOrderText.setEditable(false);
        FruitOrderText.setBackground(new java.awt.Color(255, 102, 102));
        FruitOrderText.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        FruitOrderText.setForeground(new java.awt.Color(255, 255, 255));
        FruitOrderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 3));
        FruitOrderText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FruitOrderTextActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hospital ");

        HospitalEditText.setEditable(false);
        HospitalEditText.setBackground(new java.awt.Color(255, 102, 102));
        HospitalEditText.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        HospitalEditText.setForeground(new java.awt.Color(255, 255, 255));
        HospitalEditText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 3));
        HospitalEditText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalEditTextActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Remove Data ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AmountEditText)
                            .addComponent(HospitalEditText)
                            .addComponent(OrderKeyRemove, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FruitOrderText, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderKeyRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HospitalEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FruitOrderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AmountEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(EditDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OrderKeyRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderKeyRemoveActionPerformed
        // TODO add your handling code here:

        int selectedIndex = OrderKeyRemove.getSelectedIndex();
        HospitalEditText.setText(OrderSupplies.get(selectedIndex).getHospitalName());
        AmountEditText.setText(OrderSupplies.get(selectedIndex).getAmount() + "");
        FruitOrderText.setText(OrderSupplies.get(selectedIndex).getFruitOrder());
    }//GEN-LAST:event_OrderKeyRemoveActionPerformed

    private void EditDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditDataButtonActionPerformed
        // TODO add your handling code here:
        if (HospitalEditText.getText().isEmpty() || AmountEditText.getText().isEmpty() || FruitOrderText.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Please Enter All Field!");
        }
        else {
            int selectedIndex = OrderKeyRemove.getSelectedIndex();

            OrderSupplies.remove(selectedIndex);

            saveOrderToFile();
        }
    }//GEN-LAST:event_EditDataButtonActionPerformed

    private void FruitOrderTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FruitOrderTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FruitOrderTextActionPerformed

    private void HospitalEditTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalEditTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HospitalEditTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountEditText;
    private javax.swing.JButton EditDataButton;
    private javax.swing.JTextField FruitOrderText;
    private javax.swing.JTextField HospitalEditText;
    private javax.swing.JComboBox<String> OrderKeyRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
