/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package assignmentthree;
import javax.swing.*;
import java.util.*;
import java.io.*;

/**
 *
 * @author khans
 */
public class EditFrame extends javax.swing.JFrame {
    
    ArrayList<OrderSupply> OrderSupplies;
    /** Creates new form EditFrame */
    public EditFrame() {
        initComponents();
        
        OrderSupplies = new ArrayList<OrderSupply>();
        populateArrayList();
        getContentPane().setBackground(new java.awt.Color(0,204,153));
        
        String[] orderKeyChoice =  new String[OrderSupplies.size()];
        
        for(int i = 0 ; i < OrderSupplies.size() ; i++)
        {
            orderKeyChoice[i] = OrderSupplies.get(i).getOrderKey();
        }
        OrderKeyEdit.setModel(new javax.swing.DefaultComboBoxModel<>(orderKeyChoice));
        
        OrderKeyEdit.setSelectedIndex(0);
    }
    
      public void saveOrderToFile()
    {
        try
        {
            FileOutputStream file = new FileOutputStream("order.txt");
            ObjectOutputStream outputFile = new ObjectOutputStream(file);
            
            for(int i = 0; i < OrderSupplies.size(); i++)
            {
                outputFile.writeObject(OrderSupplies.get(i));
            }
            outputFile.close();
             JOptionPane.showMessageDialog(null, "Successfully Edited!");
             this.dispose();
        }  
        catch(IOException e)
        {
           JOptionPane.showMessageDialog(null, e.getMessage());         
        }
    }
    
    public void populateArrayList(){
        try{
          FileInputStream file = new FileInputStream("order.txt");
          ObjectInputStream inputFile = new ObjectInputStream(file);
          
          boolean endOfFile = false;
          while(!endOfFile)
          {
             try
             {
               OrderSupplies.add((OrderSupply)inputFile.readObject());  
             } 
             catch(EOFException e)
             {
                endOfFile = true;
             }
             catch (Exception f) 
             {
               JOptionPane.showMessageDialog(null, f.getMessage());  
             }
          }//while
        inputFile.close(); 
        }//try
        catch(IOException e){
          JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HospitalEditText1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        HospitalEditText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AmountEditText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        OrderKeyEdit = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        EditDataButton = new javax.swing.JButton();
        FruitOrderText = new javax.swing.JTextField();

        HospitalEditText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalEditText1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 153));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hospital ");

        HospitalEditText.setBackground(new java.awt.Color(0, 255, 153));
        HospitalEditText.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        HospitalEditText.setForeground(new java.awt.Color(255, 255, 255));
        HospitalEditText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153), 3));
        HospitalEditText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalEditTextActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Order Key ");

        AmountEditText.setBackground(new java.awt.Color(0, 255, 153));
        AmountEditText.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        AmountEditText.setForeground(new java.awt.Color(255, 255, 255));
        AmountEditText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153), 3));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fruit Ordered");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Amount ");

        OrderKeyEdit.setBackground(new java.awt.Color(0, 255, 102));
        OrderKeyEdit.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 14)); // NOI18N
        OrderKeyEdit.setForeground(new java.awt.Color(255, 255, 255));
        OrderKeyEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        OrderKeyEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderKeyEditActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-edit-20.png"))); // NOI18N
        jLabel1.setText("Edit Item");

        EditDataButton.setBackground(new java.awt.Color(0, 204, 51));
        EditDataButton.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        EditDataButton.setForeground(new java.awt.Color(255, 255, 255));
        EditDataButton.setText("Edit Data ");
        EditDataButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153), 3));
        EditDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditDataButtonActionPerformed(evt);
            }
        });

        FruitOrderText.setBackground(new java.awt.Color(0, 255, 153));
        FruitOrderText.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        FruitOrderText.setForeground(new java.awt.Color(255, 255, 255));
        FruitOrderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153), 3));
        FruitOrderText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FruitOrderTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(AmountEditText)
                                .addComponent(HospitalEditText)
                                .addComponent(OrderKeyEdit, 0, 179, Short.MAX_VALUE)
                                .addComponent(FruitOrderText))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderKeyEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HospitalEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FruitOrderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AmountEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(EditDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HospitalEditTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalEditTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HospitalEditTextActionPerformed

    private void EditDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditDataButtonActionPerformed
        // TODO add your handling code here:
        if (HospitalEditText.getText().isEmpty() || AmountEditText.getText().isEmpty() || FruitOrderText.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Please Enter All Field!");
        }
        else {
            int selectedIndex = OrderKeyEdit.getSelectedIndex();
            OrderSupplies.get(selectedIndex).setHospitalName(HospitalEditText.getText().trim());
            OrderSupplies.get(selectedIndex).setFruitOrder(FruitOrderText.getText().trim());
            OrderSupplies.get(selectedIndex).setAmount(Double.parseDouble(AmountEditText.getText().trim()));
            
            saveOrderToFile();
        }
    }//GEN-LAST:event_EditDataButtonActionPerformed

    private void OrderKeyEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderKeyEditActionPerformed
        // TODO add your handling code here:
        
        int selectedIndex = OrderKeyEdit.getSelectedIndex();
        HospitalEditText.setText(OrderSupplies.get(selectedIndex).getHospitalName());
        AmountEditText.setText(OrderSupplies.get(selectedIndex).getAmount() + "");
        FruitOrderText.setText(OrderSupplies.get(selectedIndex).getFruitOrder());
        
        
    }//GEN-LAST:event_OrderKeyEditActionPerformed

    private void HospitalEditText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalEditText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HospitalEditText1ActionPerformed

    private void FruitOrderTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FruitOrderTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FruitOrderTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountEditText;
    private javax.swing.JButton EditDataButton;
    private javax.swing.JTextField FruitOrderText;
    private javax.swing.JTextField HospitalEditText;
    private javax.swing.JTextField HospitalEditText1;
    private javax.swing.JComboBox<String> OrderKeyEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

}
